### PR TITLE
Php 7.2 fixes

### PR DESCRIPTION
**Pull request by Xon**
Following functionality is [deprecated  in php 7.2](http://php.net/manual/en/migration72.deprecated.php):

- create_function()
- each()

### CODE REVIEW

**Comment by daohoangson** [comment]
Thank you @Xon

**Comment by draft1** [comment]
Waiting to be merge, so I can update my installation also.
Thanks!

**Comment by draft1** [comment]
I think it's the same as downloading from this: **https://github.com/Xon/bdMedal/tree/php7.2-fixes**

**Comment by draft1** [comment]
Thanks!
I assume that's 1.5.5 silently uploaded here
https://xfrocks.com/resources/bd-medal.34/history

**Comment by daohoangson** [comment]
@RoldanLT yes it is. And also uploaded to xenforo.com https://xenforo.com/community/resources/bd-medal.964/

**Pull request merged**
